{% set name = "perl-ball-of-hair-one" %}
{% set version = "20190704" %}
{% set makemaker_version = "7.36" %}
{% set makemaker_sha256 = "06cef6429315cdc6afa9b2dc6fbdfa33538b6f68c827f441294621858e28c558" %}
{% set datadumper_version = "2.173" %}
{% set datadumper_sha256 = "697608b39330988e519131be667ff47168aaaaf99f06bd2095d5b46ad05d76fa" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - fn: ExtUtils-MakeMaker-7.36.tar.gz
    url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-{{ makemaker_version }}.tar.gz
    sha256: {{ makemaker_sha256 }}
    folder: perl-ball-of-hair-extutils-makemaker
  - fn: Data-Dumper-2.173.tar.gz
    url: https://cpan.metacpan.org/authors/id/X/XS/XSAWYERX/Data-Dumper-{{ datadumper_version }}.tar.gz
    sha256: {{ datadumper_sha256 }}
    folder: perl-ball-of-hair-data-dumper

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
    - perl
  run:
    - perl

# Use outputs section to define output of sub packages.
outputs:
  - name: perl-ball-of-hair-one-data-dumper
    version: "{{ datadumper_version }}"
    files:
      - perl-data-dumper
    test:
      imports:
        - "Data::Dumper"

  - name: perl-ball-of-hair-one-extutils-makemaker
    version: "{{ makemaker_version }}"
    files:
      - perl-extutils-makemaker
    test:
      imports:
        - ExtUtils::Command
        - ExtUtils::Command::MM
        - ExtUtils::Liblist
        - ExtUtils::Liblist::Kid
        - ExtUtils::MM
        - ExtUtils::MM_AIX
        - ExtUtils::MM_Any
        - ExtUtils::MM_BeOS
        - ExtUtils::MM_Cygwin
        - ExtUtils::MM_DOS
        - ExtUtils::MM_Darwin
        - ExtUtils::MM_MacOS
        - ExtUtils::MM_NW5
        - ExtUtils::MM_OS2
        - ExtUtils::MM_QNX
        - ExtUtils::MM_UWIN
        - ExtUtils::MM_Unix
        - ExtUtils::MM_VMS
        - ExtUtils::MM_VOS
        - ExtUtils::MM_Win32
        - ExtUtils::MM_Win95
        - ExtUtils::MY
        - ExtUtils::MakeMaker
        - ExtUtils::MakeMaker::Config
        - ExtUtils::MakeMaker::Locale
        - ExtUtils::MakeMaker::charstar
        - ExtUtils::MakeMaker::version
        - ExtUtils::MakeMaker::version::regex
        - ExtUtils::MakeMaker::version::vpp
        - ExtUtils::Mkbootstrap
        - ExtUtils::Mksymlists
        - ExtUtils::testlib

about:
  home: https://metacpan.org/release/ExtUtils-MakeMaker
  license: perl_5
  summary: 'Multi-output module to disentangle dependencies'
